In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
df =  pd.read_csv(r'C:/Users/OMKAR/Desktop/Practice/KPMG/Uncleaned/Transactions.csv')
df.head(10)


transaction_id  product_id  customer_id transaction_date online_order  \
0               1           2         2950       25-02-2017        False   
1               2           3         3120       21-05-2017         True   
2               3          37          402       16-10-2017        False   
3               4          88         3135       31-08-2017        False   
4               5          78          787       01-10-2017         True   
5               6          25         2339       08-03-2017         True   
6               7          22         1542       21-04-2017         True   
7               8          15         2459       15-07-2017        False   
8               9          67         1305       10-08-2017        False   
9              10          12         3262       30-08-2017         True   

  order_status           brand product_line product_class product_size  \
0     Approved           Solex     Standard        medium       medium   
1     Approved   Trek Bicycles     Standard        medium        large   
2     Approved      OHM Cycles     Standard           low       medium   
3     Approved  Norco Bicycles     Standard        medium       medium   
4     Approved  Giant Bicycles     Standard        medium        large   
5     Approved  Giant Bicycles         Road        medium       medium   
6     Approved        WeareA2B     Standard        medium       medium   
7     Approved        WeareA2B     Standard        medium       medium   
8     Approved           Solex     Standard        medium        large   
9     Approved        WeareA2B     Standard        medium       medium   

   list_price standard_cost  product_first_sold_date  
0       71.49        $53.62                  41245.0  
1     2091.47       $388.92                  41701.0  
2     1793.43       $248.82                  36361.0  
3     1198.46       $381.10                  36145.0  
4     1765.30       $709.48                  42226.0  
5     1538.99       $829.65                  39031.0  
6       60.34        $45.26                  34165.0  
7     1292.84        $13.44                  39915.0  
8     1071.23       $380.74                  33455.0  
9     1231.15       $161.60                  38216.0

In [3]:
df.columns

Index(['transaction_id', 'product_id', 'customer_id', 'transaction_date',
       'online_order', 'order_status', 'brand', 'product_line',
       'product_class', 'product_size', 'list_price', 'standard_cost',
       'product_first_sold_date'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   transaction_id           20000 non-null  int64  
 1   product_id               20000 non-null  int64  
 2   customer_id              20000 non-null  int64  
 3   transaction_date         20000 non-null  object 
 4   online_order             19640 non-null  object 
 5   order_status             20000 non-null  object 
 6   brand                    19803 non-null  object 
 7   product_line             19803 non-null  object 
 8   product_class            19803 non-null  object 
 9   product_size             19803 non-null  object 
 10  list_price               20000 non-null  float64
 11  standard_cost            19803 non-null  object 
 12  product_first_sold_date  19803 non-null  float64
dtypes: float64(2), int64(3), object(8)
memory usage: 2.0+ MB


In [5]:
df.shape

(20000, 13)

### transaction_id


In [6]:
df['transaction_id'].isnull().sum()

0

In [7]:
df['transaction_id'].unique()

array([    1,     2,     3, ..., 19998, 19999, 20000], dtype=int64)

In [8]:
duplicates = df['transaction_id'].nunique() == len(df['transaction_id'])

In [9]:
print(duplicates)

True


#### product_id

In [10]:
df['product_id'].isnull().sum()

0

In [11]:
df['product_id'].unique()

array([  2,   3,  37,  88,  78,  25,  22,  15,  67,  12,   5,  61,  35,
        16,  79,  33,  54,  27,  82,  89,  64,  19,  72,  91,   1,  99,
         0,  92,  14,  44,  76,  46,  55,  66,  81,  86,  32,  77,  96,
         6,  47,  94,  93,  60,  28,   4,  38,  56,  58,  50,  80,  87,
        84,  21,  31,  62,  17,  73,  45,  49,  95,  18,  70,  26,  39,
        36,  98,  75,  42,  20,  24,  53,  65,  29,  11,  10,   7,  41,
         9,  69,  90,  97, 100,  74,  71,  34,  57,  23,  51,  59,  63,
        40,   8,  13,  30,  48,  68,  83,  43,  52,  85], dtype=int64)

In [12]:
count_zero = df[df['product_id'] == 0].shape[0]
print(count_zero)

1378


In [13]:
zero_entries = df[df['product_id'] == 0]['product_id'].tolist()
print(zero_entries)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

###  customer_id

In [14]:
df['customer_id'].isnull().sum()

0

In [15]:
df['customer_id']

0        2950
1        3120
2         402
3        3135
4         787
         ... 
19995    1018
19996     127
19997    2284
19998    2764
19999    1144
Name: customer_id, Length: 20000, dtype: int64

#### transaction_date

In [16]:
df['transaction_date']

0        25-02-2017
1        21-05-2017
2        16-10-2017
3        31-08-2017
4        01-10-2017
            ...    
19995    24-06-2017
19996    09-11-2017
19997    14-04-2017
19998    03-07-2017
19999    22-09-2017
Name: transaction_date, Length: 20000, dtype: object

In [17]:
df['transaction_date'].isnull().sum()

0

In [18]:
df['transaction_date'] =  pd.to_datetime(df['transaction_date'])

In [19]:
df['transaction_date'].dt.strftime('%d-%m-%Y')

0        25-02-2017
1        21-05-2017
2        16-10-2017
3        31-08-2017
4        10-01-2017
            ...    
19995    24-06-2017
19996    11-09-2017
19997    14-04-2017
19998    07-03-2017
19999    22-09-2017
Name: transaction_date, Length: 20000, dtype: object

In [20]:
df.columns

Index(['transaction_id', 'product_id', 'customer_id', 'transaction_date',
       'online_order', 'order_status', 'brand', 'product_line',
       'product_class', 'product_size', 'list_price', 'standard_cost',
       'product_first_sold_date'],
      dtype='object')

### inserting new column transaction_month

In [21]:
df['transaction_month'] = df['transaction_date'].dt.strftime('%B')

In [22]:
df.head()

transaction_id  product_id  customer_id transaction_date online_order  \
0               1           2         2950       2017-02-25        False   
1               2           3         3120       2017-05-21         True   
2               3          37          402       2017-10-16        False   
3               4          88         3135       2017-08-31        False   
4               5          78          787       2017-01-10         True   

  order_status           brand product_line product_class product_size  \
0     Approved           Solex     Standard        medium       medium   
1     Approved   Trek Bicycles     Standard        medium        large   
2     Approved      OHM Cycles     Standard           low       medium   
3     Approved  Norco Bicycles     Standard        medium       medium   
4     Approved  Giant Bicycles     Standard        medium        large   

   list_price standard_cost  product_first_sold_date transaction_month  
0       71.49        $53.62                  41245.0          February  
1     2091.47       $388.92                  41701.0               May  
2     1793.43       $248.82                  36361.0           October  
3     1198.46       $381.10                  36145.0            August  
4     1765.30       $709.48                  42226.0           January

### online_order

In [23]:
df['online_order']

0        False
1         True
2        False
3        False
4         True
         ...  
19995     True
19996     True
19997     True
19998    False
19999     True
Name: online_order, Length: 20000, dtype: object

In [24]:
df['online_order'].isnull().sum()

360

In [25]:
df['online_order'].unique()

array([False, True, nan], dtype=object)

In [26]:
df['online_order'] = df['online_order'].fillna("Unknown")

In [27]:
df['online_order'].unique()

array([False, True, 'Unknown'], dtype=object)

In [28]:
df['online_order'].isnull().sum()

0

### order_status

In [29]:
df['order_status']

0        Approved
1        Approved
2        Approved
3        Approved
4        Approved
           ...   
19995    Approved
19996    Approved
19997    Approved
19998    Approved
19999    Approved
Name: order_status, Length: 20000, dtype: object

In [30]:
df['order_status'].isnull().sum()

0

In [31]:
df['order_status'].unique()

array(['Approved', 'Cancelled'], dtype=object)

### brand

In [32]:
df['brand']

0                 Solex
1         Trek Bicycles
2            OHM Cycles
3        Norco Bicycles
4        Giant Bicycles
              ...      
19995        OHM Cycles
19996             Solex
19997        OHM Cycles
19998        OHM Cycles
19999     Trek Bicycles
Name: brand, Length: 20000, dtype: object

In [33]:
df['brand'].isnull().sum()

197

In [34]:
df['brand'].unique()

array(['Solex', 'Trek Bicycles', 'OHM Cycles', 'Norco Bicycles',
       'Giant Bicycles', 'WeareA2B', nan], dtype=object)

In [35]:
df['brand'] = df['brand'].fillna("Not Recorded")

In [36]:
df['brand'].unique()

array(['Solex', 'Trek Bicycles', 'OHM Cycles', 'Norco Bicycles',
       'Giant Bicycles', 'WeareA2B', 'Not Recorded'], dtype=object)

In [37]:
df['brand'].isnull().sum()

0

### product_line

In [38]:
df['product_line']

0        Standard
1        Standard
2        Standard
3        Standard
4        Standard
           ...   
19995    Standard
19996        Road
19997    Standard
19998    Standard
19999    Standard
Name: product_line, Length: 20000, dtype: object

In [39]:
df['product_line'].isnull().sum()

197

In [40]:
df['product_line'].unique()

array(['Standard', 'Road', 'Mountain', 'Touring', nan], dtype=object)

In [41]:
df['product_line'] = df['product_line'].fillna('Not Recorded')

In [42]:
df['product_line'].unique()

array(['Standard', 'Road', 'Mountain', 'Touring', 'Not Recorded'],
      dtype=object)

### product_class


In [43]:
df['product_class']

0        medium
1        medium
2           low
3        medium
4        medium
          ...  
19995      high
19996    medium
19997    medium
19998      high
19999    medium
Name: product_class, Length: 20000, dtype: object

In [44]:
df['product_class'].isnull().sum()

197

In [45]:
df['product_class'].unique()

array(['medium', 'low', 'high', nan], dtype=object)

In [46]:
df['product_class'] = df['product_class'].fillna('not recorded')

In [47]:
df['product_class'].unique()


array(['medium', 'low', 'high', 'not recorded'], dtype=object)

### product_size 

In [48]:
df['product_size']

0        medium
1         large
2        medium
3        medium
4         large
          ...  
19995    medium
19996    medium
19997    medium
19998    medium
19999     small
Name: product_size, Length: 20000, dtype: object

In [49]:
df['product_size'].isnull().sum()

197

In [50]:
df['product_size'].unique()

array(['medium', 'large', 'small', nan], dtype=object)

In [51]:
df['product_size'] = df['product_size'].fillna('not recorded')

In [52]:
df['product_size'].unique()

array(['medium', 'large', 'small', 'not recorded'], dtype=object)

### list_price and standard_cost columns

In [53]:
df.columns

Index(['transaction_id', 'product_id', 'customer_id', 'transaction_date',
       'online_order', 'order_status', 'brand', 'product_line',
       'product_class', 'product_size', 'list_price', 'standard_cost',
       'product_first_sold_date', 'transaction_month'],
      dtype='object')

In [54]:
df['list_price']

0          71.49
1        2091.47
2        1793.43
3        1198.46
4        1765.30
          ...   
19995    2005.66
19996     416.98
19997    1636.90
19998     227.88
19999    1775.81
Name: list_price, Length: 20000, dtype: float64

In [55]:
df['list_price'].isnull().sum()

0

In [56]:
 df['standard_cost']

0           $53.62
1          $388.92
2          $248.82
3          $381.10
4          $709.48
           ...    
19995    $1,203.40
19996      $312.74
19997       $44.71
19998      $136.73
19999    $1,580.47
Name: standard_cost, Length: 20000, dtype: object

In [57]:
df['standard_cost'] = df['standard_cost'].str.replace('$', '')
df['standard_cost'] = df['standard_cost'].str.replace(',', '')

C:\Users\OMKAR\AppData\Local\Temp/ipykernel_836/2667797214.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['standard_cost'] = df['standard_cost'].str.replace('$', '')


In [58]:
  df['standard_cost'] = df['standard_cost'].astype(float)

In [59]:
  df['standard_cost'] 

0          53.62
1         388.92
2         248.82
3         381.10
4         709.48
          ...   
19995    1203.40
19996     312.74
19997      44.71
19998     136.73
19999    1580.47
Name: standard_cost, Length: 20000, dtype: float64

In [60]:
df['profit'] = df['list_price'] -  df['standard_cost']

In [61]:
df.head()

transaction_id  product_id  customer_id transaction_date online_order  \
0               1           2         2950       2017-02-25        False   
1               2           3         3120       2017-05-21         True   
2               3          37          402       2017-10-16        False   
3               4          88         3135       2017-08-31        False   
4               5          78          787       2017-01-10         True   

  order_status           brand product_line product_class product_size  \
0     Approved           Solex     Standard        medium       medium   
1     Approved   Trek Bicycles     Standard        medium        large   
2     Approved      OHM Cycles     Standard           low       medium   
3     Approved  Norco Bicycles     Standard        medium       medium   
4     Approved  Giant Bicycles     Standard        medium        large   

   list_price  standard_cost  product_first_sold_date transaction_month  \
0       71.49          53.62                  41245.0          February   
1     2091.47         388.92                  41701.0               May   
2     1793.43         248.82                  36361.0           October   
3     1198.46         381.10                  36145.0            August   
4     1765.30         709.48                  42226.0           January   

    profit  
0    17.87  
1  1702.55  
2  1544.61  
3   817.36  
4  1055.82

### product_first_sold_date

In [62]:
df['product_first_sold_date'].isnull().sum()

197

In [63]:
df['product_first_sold_date'].unique()

array([41245., 41701., 36361., 36145., 42226., 39031., 34165., 39915.,
       33455., 38216., 40784., 42172., 34527., 34586., 38193., 37873.,
       38206., 33888., 37337., 36334., 42145., 42404., 34079., 41047.,
       42560., 42710., 41922., 37539., 42688., 38991., 38647., 37874.,
       34996., 33549., 38693., 37668., 41533., 41009., 40553., 39427.,
       38482., 35470., 41434., 36367., 38750., 41848., 34244., 42696.,
       38258., 41167., 40672., 35707., 42295., 33552., 35667., 33879.,
       40670., 37626., 38339., 40303., 34143., 35160., 36668., 36498.,
       34071., 40649., 37823., 36146., 42105., 34115., 35052., 33364.,
       42218., 41345., 33429., 38859.,    nan, 36833., 37499., 41064.,
       33259., 35560., 37838., 37698., 35378., 38573., 38002., 39526.,
       39880., 40487., 40336., 40618., 34170., 40410., 42458., 39298.,
       35455., 37220., 37659., 40779., 34556.])

In [64]:
df['product_first_sold_date'] = pd.to_datetime(df['product_first_sold_date'], unit='s')
df['product_first_sold_date'].head()

0   1970-01-01 11:27:25
1   1970-01-01 11:35:01
2   1970-01-01 10:06:01
3   1970-01-01 10:02:25
4   1970-01-01 11:43:46
Name: product_first_sold_date, dtype: datetime64[ns]

In [66]:
df = df.to_csv('C:/Users/OMKAR/Desktop/Practice/KPMG/Cleaned/Transactions.csv', index = False)